[package]
name = "shrivenquant-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }

[build-dependencies]
tonic-build = "0.12"