# cargo-deny configuration for ShrivenQ
# This ensures we maintain control over our dependency tree

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Allow specific duplicate versions that we've reviewed and accepted
skip = [
    # These are pulled in by tracing-subscriber and are safe
    { name = "regex-automata", version = "0.1" },
    { name = "regex-syntax", version = "0.6" },
    # Windows dependencies have multiple versions but only compile on Windows
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
    { name = "wasi" },
]

[licenses]
# List of allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

[sources]
# Ensure we only use crates.io and our own code
allow-git = []
