[package]
name = "trading-gateway"
version = "0.1.0"
edition = "2024"
authors = ["ShrivenQuant Team"]
description = "World-class trading orchestrator with orderbook integration"

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Async runtime
tokio = { version = "1.47", features = ["full"] }
tokio-stream = "0.1"
async-trait = "0.1"

# Web framework
axum = "0.7"

# gRPC
tonic = { workspace = true }
prost = { workspace = true }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Performance
crossbeam = "0.8"
parking_lot = "0.12"
dashmap = "6.1"
arc-swap = "1.7"
fxhash = "0.2"
rustc-hash = "2.0"

# Time
chrono = { version = "0.4", features = ["serde"] }

# Metrics and monitoring
metrics = "0.23"
metrics-exporter-prometheus = "0.15"

# Internal dependencies
services-common = { path = "../common" }

orderbook = { path = "../orderbook" }
risk-manager = { path = "../risk-manager" }
execution-router = { path = "../execution-router" }
data-aggregator = { path = "../data-aggregator" }

# Circuit breaker functionality is implemented internally

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
rstest = "0.21"
tokio-test = "0.4"