[package]
name = "perf"
version = "0.1.0"
edition = "2024"
authors = ["Praveen Ayyasola <praveenkumar.avln@gmail.com>"]
license = "Proprietary"
repository = "https://github.com/praveen686/shrivenQ"
description = "Performance testing tools for ShrivenQ"
readme = "../README.md"
keywords = ["trading", "performance", "testing"]
categories = ["finance"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
hdrhistogram = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
# Force base64 version to align with reqwest
base64 = { workspace = true }
# Force regex versions to align
regex = { workspace = true }
storage = { path = "../../infra/storage" }
common = { path = "../../core/common" }

[dev-dependencies]
criterion = { workspace = true }

[[bin]]
name = "sq-perf"
path = "src/main.rs"
