[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"
authors = ["ShrivenQuant Team"]

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"

# Performance
crossbeam = "0.8"
parking_lot = "0.12"
smallvec = "1.13"
arrayvec = "0.7"
ahash = "0.8"

# SIMD operations
packed_simd_2 = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rkyv = { version = "0.7", features = ["validation"] }

# Time handling  
chrono = "0.4"

# Metrics
metrics = "0.23"
hdrhistogram = "7.5"

# Internal
common = { path = "../../core/common" }

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
quickcheck = "1.0"
rand = "0.8"

[[bench]]
name = "orderbook_bench"
harness = false

[features]
default = ["simd"]
simd = ["packed_simd_2"]
replay = []
analytics = []