[package]
name = "sq-compliance"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ignore = "0.4"
rayon = "1.10"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "2"
globset = "0.4"
toml = "0.8"
rustc-hash = "2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace]