[package]
name = "trading-strategies"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures-util = "0.3"
tokio-tungstenite = "0.21"

# Internal
services-common = { path = "../common" }

# Trading logic
dashmap = "6.1"
parking_lot = "0.12"

[build-dependencies]
tonic-prost-build = "0.14"