[package]
name = "sq-remediator"
version = "0.1.0"
edition = "2024"
authors = ["ShrivenQuant Team"]
description = "Automatic compliance violation remediation for ShrivenQuant"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
ignore = "0.4"
rayon = "1.10"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
walkdir = "2.5"
tree-sitter = "0.24"
tree-sitter-rust = "0.24"
tempfile = "3.14"
rustc-hash = "2.0"

[profile.release]
lto = true
codegen-units = 1