[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "ShrivenQ engine module"
readme = "../README.md"
keywords = ["trading", "engine"]
categories = ["finance"]

[dependencies]
common = { path = "../../core/common" }
bus = { path = "../../infra/bus" }
storage = { path = "../../infra/storage" }
lob = { path = "../../market-data/lob" }
feeds = { path = "../../market-data/feeds" }
auth = { path = "../../infra/auth" }

# Async runtime
tokio = { workspace = true }
async-trait = "0.1"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }

# Time handling
chrono = { workspace = true }

# Data structures
dashmap = "6.0"
indexmap = "2.0"
smallvec = "1.15"

# Math
statrs = "0.17"

# Logging
tracing = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# UUID for order IDs
uuid = { version = "1.11", features = ["v4", "serde"] }

[dev-dependencies]
criterion = { workspace = true }
proptest = "1.0"
tokio-test = "0.4"
rstest = "0.18"
