[package]
name = "sim"
version.workspace = true
edition = "2024"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "ShrivenQ sim module"
readme = "../README.md"
keywords = ["trading", "sim"]
categories = ["finance"]

[dependencies]
common = { path = "../../core/common" }
bus = { path = "../../infra/bus" }
storage = { path = "../../infra/storage" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
